### ISSUE TITLE
"relocation R_X86_64_PC32 against symbol" error

### ISSUE THREAD

**Issue by espe-CV** [ealeelab/rtea#1]
Hi,
Thanks for developing the tool. 

I tried to run the pipeline using docker containers (built by myself) and I'm getting the following error:

`Rscript /tmp/genomics-commons-setup/rtea/run_ctea.R \
 -b /app/rTea/test_results/bam/test_sample.hisat2.bam \
 -o /app/rTea/test_results/ctea/test_sample \
 -t 8
Bioconductor version '3.10' is out-of-date; the current release version '3.18'
  is available with R version '4.3'; see https://bioconductor.org/install
Loading required package: Rcpp
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG   -I"/usr/local/lib/R/site-library/Rcpp/include" -I"/tmp/genomics-commons-setup/rtea/ctea" -I/usr/local/include -I /usr/local/include/bamtools -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c clippedSequence.cpp -o clippedSequence.o
g++ -std=gnu++11 -shared -L/usr/local/lib/R/lib -L/usr/local/lib -o sourceCpp_2.so clippedSequence.o -L /usr/local/lib -lbamtools -L/usr/local/lib/R/lib -lR
/usr/bin/ld: /usr/local/lib/libbamtools.a(BgzfStream_p.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTVN8BamTools8Internal12BamExceptionE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libbamtools.a(BamException_p.cpp.o): relocation R_X86_64_PC32 against symbol `_ZN8BamTools8Internal12BamException9SEPARATORB5cxx11E' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libbamtools.a(BamHeader_p.cpp.o): relocation R_X86_64_PC32 against symbol `_ZN8BamTools8Internal12BamExceptionD1Ev' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libbamtools.a(BamRandomAccessController_p.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTTNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE@@GLIBCXX_3.4.21' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libbamtools.a(BamStandardIndex_p.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTVN8BamTools8Internal16BamStandardIndexE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libbamtools.a(BamToolsIndex_p.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTVN8BamTools8Internal13BamToolsIndexE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libbamtools.a(BamFile_p.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTVN8BamTools8Internal7BamFileE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libbamtools.a(BamFtp_p.cpp.o): relocation R_X86_64_PC32 against symbol `_ZNK8BamTools8Internal6BamFtp6IsOpenEv' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libbamtools.a(BamHttp_p.cpp.o): relocation R_X86_64_PC32 against symbol `_ZNK8BamTools8Internal7BamHttp6IsOpenEv' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libbamtools.a(BamPipe_p.cpp.o): relocation R_X86_64_PC32 against symbol `_ZGVZN8BamTools12IBamIODevice14SetErrorStringERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_E9SEPARATORB5cxx11' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libbamtools.a(HttpHeader_p.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTVN8BamTools8Internal10HttpHeaderE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libbamtools.a(ILocalIODevice_p.cpp.o): relocation R_X86_64_PC32 against symbol `_ZNK8BamTools12IBamIODevice6IsOpenEv' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libbamtools.a(TcpSocket_p.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTVSt9basic_iosIcSt11char_traitsIcEE@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libbamtools.a(SamHeader.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTTNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE@@GLIBCXX_3.4.21' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libbamtools.a(SamProgramChain.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTVN8BamTools8Internal12BamExceptionE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libbamtools.a(HostAddress_p.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTTNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE@@GLIBCXX_3.4.21' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libbamtools.a(SamFormatParser_p.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTVSt9basic_iosIcSt11char_traitsIcEE@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libbamtools.a(SamFormatPrinter_p.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTVSt9basic_iosIcSt11char_traitsIcEE@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libbamtools.a(SamHeaderValidator_p.cpp.o): relocation R_X86_64_PC32 against symbol `_ZNKSt5ctypeIcE8do_widenEc' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libbamtools.a(SamSequence.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTVSt9basic_iosIcSt11char_traitsIcEE@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
make: *** [/usr/local/lib/R/share/make/shlib.mk:6: sourceCpp_2.so] Error 1
Error in sourceCpp(clipcpp) : Error 1 occurred building shared library.
Calls: sys.source -> eval -> eval -> sourceCpp
5: stop("Error ", status, " occurred building shared library.")
4: sourceCpp(clipcpp)
3: eval(exprs[i], envir)`

So far, I tried two different containers:

1. Debian, using R3.6.2 (bioconductor/release_base2:R3.6.2_Bioc3.10)
2. Ubuntu, using R4.1.2 (ubuntu:22.04)

I followed your instructions to install all the dependencies, and I'm getting the same error in both cases. 

Is there something I'm missing? 

@junseokpark 
@boramlee85 
@ShaynaMallett

**Comment by junseokpark** [comment]
Hi, @espe-CV.

I have updated the Dockerfile to resolve the issue. You can either build your own rTea image with the new Dockerfile, or you can download Docker images from [https://hub.docker.com/repository/docker/junseokpark/rtea.](https://hub.docker.com/repository/docker/junseokpark/rtea).

The previous Dockerfile had a GPG key issue due to R-base:3.6.2. We manually added the installation steps for curl and GnuPG to address the problem.

Feel free to use rTea based on the updated Docker image.

Thank you.
